include: package:very_good_analysis/analysis_options.yaml

# ========================== # --- IGNORE ---
linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
analyzer:
  errors:
    invalid_annotation_target: ignore
